name: Deploy to gh-pages-new branch

on:
  push:
    branches: [ astro ] # Trigger on pushes to the astro branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure all history is fetched

      - name: Setup Git config
        run: |
          git config user.name "treemcgee42"
          git config user.email "varun.malladi@gmail.com"

      - name: Check if gh-pages-new branch exists
        id: check_branch
        run: |
          if git rev-parse --verify origin/gh-pages-new; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      - name: Create the new branch or reset if exists
        if: steps.check_branch.outputs.exists == 'false'
        run: |
          git checkout --orphan gh-pages-new
          git reset --hard
          git commit --allow-empty -m "Initial commit on gh-pages-new branch"
          git push origin gh-pages-new -u

      - name: Copy desired directories to root of new branch
        if: steps.check_branch.outputs.exists == 'true'
        run: |
          git fetch
          git checkout gh-pages-new
          git rm -rf .  # This clears out the existing contents
          git checkout astro -- astro/
          git checkout astro -- .github/
          git mv -k astro/* . || true  # The '|| true' ensures that the command doesn't fail if there's nothing to move
          git mv -k astro/.* . || true  # This moves hidden files as well
          git commit -m "Populate gh-pages-new branch with content from astro/ and .github/" || true  # This commits only if there are changes
          git push origin gh-pages-new -u
